// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: mapreduce.proto

package mapreduce

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapReduceTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag:form:"input" uri:"input"
	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty" form:"input" uri:"input"`
	// @inject_tag:form:"task_state" uri:"task_state"
	TaskState int64 `protobuf:"varint,2,opt,name=task_state,json=taskState,proto3" json:"task_state,omitempty" form:"task_state" uri:"task_state"`
	// @inject_tag:form:"n_reducer" uri:"n_reducer"
	NReducer int64 `protobuf:"varint,3,opt,name=n_reducer,json=nReducer,proto3" json:"n_reducer,omitempty" form:"n_reducer" uri:"n_reducer"`
	// @inject_tag:form:"task_number" uri:"task_number"
	TaskNumber int64 `protobuf:"varint,4,opt,name=task_number,json=taskNumber,proto3" json:"task_number,omitempty" form:"task_number" uri:"task_number"`
	// @inject_tag:form:"intermediates" uri:"intermediates"
	Intermediates []string `protobuf:"bytes,5,rep,name=intermediates,proto3" json:"intermediates,omitempty" form:"intermediates" uri:"intermediates"`
	// @inject_tag:form:"output" uri:"output"
	Output string `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty" form:"output" uri:"output"`
}

func (x *MapReduceTask) Reset() {
	*x = MapReduceTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapReduceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReduceTask) ProtoMessage() {}

func (x *MapReduceTask) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReduceTask.ProtoReflect.Descriptor instead.
func (*MapReduceTask) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *MapReduceTask) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *MapReduceTask) GetTaskState() int64 {
	if x != nil {
		return x.TaskState
	}
	return 0
}

func (x *MapReduceTask) GetNReducer() int64 {
	if x != nil {
		return x.NReducer
	}
	return 0
}

func (x *MapReduceTask) GetTaskNumber() int64 {
	if x != nil {
		return x.TaskNumber
	}
	return 0
}

func (x *MapReduceTask) GetIntermediates() []string {
	if x != nil {
		return x.Intermediates
	}
	return nil
}

func (x *MapReduceTask) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type MasterTaskCompletedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag:form:"code" uri:"code"
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" form:"code" uri:"code"`
	// @inject_tag:form:"message" uri:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" form:"message" uri:"message"`
}

func (x *MasterTaskCompletedResp) Reset() {
	*x = MasterTaskCompletedResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterTaskCompletedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterTaskCompletedResp) ProtoMessage() {}

func (x *MasterTaskCompletedResp) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterTaskCompletedResp.ProtoReflect.Descriptor instead.
func (*MasterTaskCompletedResp) Descriptor() ([]byte, []int) {
	return file_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *MasterTaskCompletedResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MasterTaskCompletedResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mapreduce_proto protoreflect.FileDescriptor

var file_mapreduce_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x5f, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x22, 0x47, 0x0a, 0x17, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61,
	0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x87, 0x01,
	0x0a, 0x10, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x32, 0x0a, 0x10, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0e, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3f, 0x0a, 0x13, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x2e,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x18, 0x2e,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x6d, 0x61, 0x70, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapreduce_proto_rawDescOnce sync.Once
	file_mapreduce_proto_rawDescData = file_mapreduce_proto_rawDesc
)

func file_mapreduce_proto_rawDescGZIP() []byte {
	file_mapreduce_proto_rawDescOnce.Do(func() {
		file_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapreduce_proto_rawDescData)
	})
	return file_mapreduce_proto_rawDescData
}

var file_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mapreduce_proto_goTypes = []interface{}{
	(*MapReduceTask)(nil),           // 0: MapReduceTask
	(*MasterTaskCompletedResp)(nil), // 1: MasterTaskCompletedResp
}
var file_mapreduce_proto_depIdxs = []int32{
	0, // 0: MapReduceService.MasterAssignTask:input_type -> MapReduceTask
	0, // 1: MapReduceService.MasterTaskCompleted:input_type -> MapReduceTask
	0, // 2: MapReduceService.MasterAssignTask:output_type -> MapReduceTask
	1, // 3: MapReduceService.MasterTaskCompleted:output_type -> MasterTaskCompletedResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mapreduce_proto_init() }
func file_mapreduce_proto_init() {
	if File_mapreduce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapreduce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapReduceTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterTaskCompletedResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapreduce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapreduce_proto_goTypes,
		DependencyIndexes: file_mapreduce_proto_depIdxs,
		MessageInfos:      file_mapreduce_proto_msgTypes,
	}.Build()
	File_mapreduce_proto = out.File
	file_mapreduce_proto_rawDesc = nil
	file_mapreduce_proto_goTypes = nil
	file_mapreduce_proto_depIdxs = nil
}
