// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: favoriteModels.pb

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoritesModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"favorite_id"
	FavoriteID uint32 `protobuf:"varint,1,opt,name=FavoriteID,proto3" json:"FavoriteID,omitempty"`
	// @inject_tag: json:"user_id"
	UserID uint32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// @inject_tag: json:"favorite_name"
	FavoriteName string `protobuf:"bytes,3,opt,name=FavoriteName,proto3" json:"FavoriteName,omitempty"`
	// @inject_tag: json:"url_info"
	UrlInfo []*UrlModel `protobuf:"bytes,4,rep,name=UrlInfo,proto3" json:"UrlInfo,omitempty"`
}

func (x *FavoritesModel) Reset() {
	*x = FavoritesModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoriteModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoritesModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoritesModel) ProtoMessage() {}

func (x *FavoritesModel) ProtoReflect() protoreflect.Message {
	mi := &file_favoriteModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoritesModel.ProtoReflect.Descriptor instead.
func (*FavoritesModel) Descriptor() ([]byte, []int) {
	return file_favoriteModels_proto_rawDescGZIP(), []int{0}
}

func (x *FavoritesModel) GetFavoriteID() uint32 {
	if x != nil {
		return x.FavoriteID
	}
	return 0
}

func (x *FavoritesModel) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *FavoritesModel) GetFavoriteName() string {
	if x != nil {
		return x.FavoriteName
	}
	return ""
}

func (x *FavoritesModel) GetUrlInfo() []*UrlModel {
	if x != nil {
		return x.UrlInfo
	}
	return nil
}

type UrlModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"url_id"
	UrlID uint32 `protobuf:"varint,5,opt,name=UrlID,proto3" json:"UrlID,omitempty"`
	// @inject_tag: json:"url"
	Url string `protobuf:"bytes,6,opt,name=Url,proto3" json:"Url,omitempty"`
	// @inject_tag: json:"desc"
	Desc string `protobuf:"bytes,7,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *UrlModel) Reset() {
	*x = UrlModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favoriteModels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlModel) ProtoMessage() {}

func (x *UrlModel) ProtoReflect() protoreflect.Message {
	mi := &file_favoriteModels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlModel.ProtoReflect.Descriptor instead.
func (*UrlModel) Descriptor() ([]byte, []int) {
	return file_favoriteModels_proto_rawDescGZIP(), []int{1}
}

func (x *UrlModel) GetUrlID() uint32 {
	if x != nil {
		return x.UrlID
	}
	return 0
}

func (x *UrlModel) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlModel) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_favoriteModels_proto protoreflect.FileDescriptor

var file_favoriteModels_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x94, 0x01, 0x0a, 0x0e, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x55, 0x72, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x72, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x07, 0x55, 0x72, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x46, 0x0a, 0x08, 0x55, 0x72, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x55, 0x72, 0x6c, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x55, 0x72,
	0x6c, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_favoriteModels_proto_rawDescOnce sync.Once
	file_favoriteModels_proto_rawDescData = file_favoriteModels_proto_rawDesc
)

func file_favoriteModels_proto_rawDescGZIP() []byte {
	file_favoriteModels_proto_rawDescOnce.Do(func() {
		file_favoriteModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_favoriteModels_proto_rawDescData)
	})
	return file_favoriteModels_proto_rawDescData
}

var file_favoriteModels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_favoriteModels_proto_goTypes = []interface{}{
	(*FavoritesModel)(nil), // 0: pb.FavoritesModel
	(*UrlModel)(nil),       // 1: pb.UrlModel
}
var file_favoriteModels_proto_depIdxs = []int32{
	1, // 0: pb.FavoritesModel.UrlInfo:type_name -> pb.UrlModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_favoriteModels_proto_init() }
func file_favoriteModels_proto_init() {
	if File_favoriteModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_favoriteModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoritesModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favoriteModels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_favoriteModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_favoriteModels_proto_goTypes,
		DependencyIndexes: file_favoriteModels_proto_depIdxs,
		MessageInfos:      file_favoriteModels_proto_msgTypes,
	}.Build()
	File_favoriteModels_proto = out.File
	file_favoriteModels_proto_rawDesc = nil
	file_favoriteModels_proto_goTypes = nil
	file_favoriteModels_proto_depIdxs = nil
}
