// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: search_vector.proto

package search_vector

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchVectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: form:"query" uri:"query"
	Query []string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" form:"query" uri:"query"`
}

func (x *SearchVectorRequest) Reset() {
	*x = SearchVectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_vector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorRequest) ProtoMessage() {}

func (x *SearchVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_vector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorRequest.ProtoReflect.Descriptor instead.
func (*SearchVectorRequest) Descriptor() ([]byte, []int) {
	return file_search_vector_proto_rawDescGZIP(), []int{0}
}

func (x *SearchVectorRequest) GetQuery() []string {
	if x != nil {
		return x.Query
	}
	return nil
}

type SearchVectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DocIds []string `protobuf:"bytes,2,rep,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	Msg    string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Error  string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SearchVectorResponse) Reset() {
	*x = SearchVectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_vector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorResponse) ProtoMessage() {}

func (x *SearchVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_vector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorResponse.ProtoReflect.Descriptor instead.
func (*SearchVectorResponse) Descriptor() ([]byte, []int) {
	return file_search_vector_proto_rawDescGZIP(), []int{1}
}

func (x *SearchVectorResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchVectorResponse) GetDocIds() []string {
	if x != nil {
		return x.DocIds
	}
	return nil
}

func (x *SearchVectorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchVectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_search_vector_proto protoreflect.FileDescriptor

var file_search_vector_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0x6b, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0x52, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_search_vector_proto_rawDescOnce sync.Once
	file_search_vector_proto_rawDescData = file_search_vector_proto_rawDesc
)

func file_search_vector_proto_rawDescGZIP() []byte {
	file_search_vector_proto_rawDescOnce.Do(func() {
		file_search_vector_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_vector_proto_rawDescData)
	})
	return file_search_vector_proto_rawDescData
}

var file_search_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search_vector_proto_goTypes = []interface{}{
	(*SearchVectorRequest)(nil),  // 0: SearchVectorRequest
	(*SearchVectorResponse)(nil), // 1: SearchVectorResponse
}
var file_search_vector_proto_depIdxs = []int32{
	0, // 0: SearchVectorService.SearchVector:input_type -> SearchVectorRequest
	1, // 1: SearchVectorService.SearchVector:output_type -> SearchVectorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_vector_proto_init() }
func file_search_vector_proto_init() {
	if File_search_vector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_search_vector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_vector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_vector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_vector_proto_goTypes,
		DependencyIndexes: file_search_vector_proto_depIdxs,
		MessageInfos:      file_search_vector_proto_msgTypes,
	}.Build()
	File_search_vector_proto = out.File
	file_search_vector_proto_rawDesc = nil
	file_search_vector_proto_goTypes = nil
	file_search_vector_proto_depIdxs = nil
}
