# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import search_vector_pb2 as search__vector__pb2


class SearchVectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchVector = channel.unary_unary(
                '/SearchVectorService/SearchVector',
                request_serializer=search__vector__pb2.SearchVectorRequest.SerializeToString,
                response_deserializer=search__vector__pb2.SearchVectorResponse.FromString)


class SearchVectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchVectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVector,
                    request_deserializer=search__vector__pb2.SearchVectorRequest.FromString,
                    response_serializer=search__vector__pb2.SearchVectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SearchVectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchVectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SearchVectorService/SearchVector',
            search__vector__pb2.SearchVectorRequest.SerializeToString,
            search__vector__pb2.SearchVectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
