// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: vector_retrieval.proto

package vector_retrieval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag:form:"k" uri:"k"
	K int64 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty" form:"k" uri:"k"`
	// @inject_tag:form:"vector" uri:"vector"
	Vector []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty" form:"vector" uri:"vector"`
}

func (x *VectorReq) Reset() {
	*x = VectorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vector_retrieval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorReq) ProtoMessage() {}

func (x *VectorReq) ProtoReflect() protoreflect.Message {
	mi := &file_vector_retrieval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorReq.ProtoReflect.Descriptor instead.
func (*VectorReq) Descriptor() ([]byte, []int) {
	return file_vector_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *VectorReq) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *VectorReq) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type VectorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retval []int64   `protobuf:"varint,1,rep,packed,name=retval,proto3" json:"retval,omitempty"`
	Scores []float32 `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	Labels []string  `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *VectorResp) Reset() {
	*x = VectorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vector_retrieval_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResp) ProtoMessage() {}

func (x *VectorResp) ProtoReflect() protoreflect.Message {
	mi := &file_vector_retrieval_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResp.ProtoReflect.Descriptor instead.
func (*VectorResp) Descriptor() ([]byte, []int) {
	return file_vector_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *VectorResp) GetRetval() []int64 {
	if x != nil {
		return x.Retval
	}
	return nil
}

func (x *VectorResp) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *VectorResp) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_vector_retrieval_proto protoreflect.FileDescriptor

var file_vector_retrieval_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x6b, 0x12, 0x1a, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22,
	0x5c, 0x0a, 0x0a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a,
	0x06, 0x72, 0x65, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x10,
	0x01, 0x52, 0x06, 0x72, 0x65, 0x74, 0x76, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x06, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x32, 0x34, 0x0a,
	0x0f, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c,
	0x12, 0x21, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0a, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x72,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vector_retrieval_proto_rawDescOnce sync.Once
	file_vector_retrieval_proto_rawDescData = file_vector_retrieval_proto_rawDesc
)

func file_vector_retrieval_proto_rawDescGZIP() []byte {
	file_vector_retrieval_proto_rawDescOnce.Do(func() {
		file_vector_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(file_vector_retrieval_proto_rawDescData)
	})
	return file_vector_retrieval_proto_rawDescData
}

var file_vector_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vector_retrieval_proto_goTypes = []interface{}{
	(*VectorReq)(nil),  // 0: VectorReq
	(*VectorResp)(nil), // 1: VectorResp
}
var file_vector_retrieval_proto_depIdxs = []int32{
	0, // 0: VectorRetrieval.Search:input_type -> VectorReq
	1, // 1: VectorRetrieval.Search:output_type -> VectorResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vector_retrieval_proto_init() }
func file_vector_retrieval_proto_init() {
	if File_vector_retrieval_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vector_retrieval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vector_retrieval_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vector_retrieval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_retrieval_proto_goTypes,
		DependencyIndexes: file_vector_retrieval_proto_depIdxs,
		MessageInfos:      file_vector_retrieval_proto_msgTypes,
	}.Build()
	File_vector_retrieval_proto = out.File
	file_vector_retrieval_proto_rawDesc = nil
	file_vector_retrieval_proto_goTypes = nil
	file_vector_retrieval_proto_depIdxs = nil
}
